[package]
name = "social-recovery"
version = "0.1.0"
authors = ["Nadav Ivgi <nadav@shesek.info>"]
edition = "2018"

[dependencies]
minsc = { path = "/workspace/minsc" }
rand = "0.8.5"
serde = "1.0.136"
bincode = "1.3.3"
sharks = "0.5.0"
lazy_static = "1.4.0"